/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c ServerDBus -a serverdbus.h:serverdbus.cpp simpleInterface.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "serverdbus.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class ServerDBus
 */

ServerDBus::ServerDBus(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

ServerDBus::~ServerDBus()
{
    // destructor
}

void ServerDBus::SayBye()
{
    // handle method call com.nokia.Demo.SayBye
    QMetaObject::invokeMethod(parent(), "SayBye");
}

void ServerDBus::SayHello(const QString &name, const QVariantMap &customdata)
{
    // handle method call com.nokia.Demo.SayHello
    QMetaObject::invokeMethod(parent(), "SayHello", Q_ARG(QString, name), Q_ARG(QVariantMap, customdata));
}

